### ISSUE TITLE
React Navigation (Version Issues)

### ISSUE THREAD

**Issue by Vishaldhanotiya** [melihberberolu/react-native-scaling-drawer#13]
there is react native  navigation version issue. it is not working with new version of react-navigation 

Cannot call a class as a function
_classCallCheck
    index.delta?platform=android&dev=true&minify=false:64832:114
Navigator
    index.delta?platform=android&dev=true&minify=false:64869:24
<unknown>
    index.delta?platform=android&dev=true&minify=false:61590:121
loadModuleImplementation
    index.delta?platform=android&dev=true&minify=false:159:14
guardedLoadModule
    index.delta?platform=android&dev=true&minify=false:92:38
_require
    index.delta?platform=android&dev=true&minify=false:73:79
<unknown>
    index.delta?platform=android&dev=true&minify=false:61306:31
loadModuleImplementation
    index.delta?platform=android&dev=true&minify=false:159:14
guardedLoadModule
    index.delta?platform=android&dev=true&minify=false:92:38
_require
    index.delta?platform=android&dev=true&minify=false:73:79
<unknown>
    index.delta?platform=android&dev=true&minify=false:1426:22
loadModuleImplementation
    index.delta?platform=android&dev=true&minify=false:159:14
guardedLoadModule
    index.delta?platform=android&dev=true&minify=false:84:47
_require
    index.delta?platform=android&dev=true&minify=false:73:79
global code
    index.delta?platform=android&dev=true&minify=false:101645:8

**Comment by melihberberolu** [comment]
#15
