### ISSUE TITLE
Transition when navigate to other screen

### ISSUE THREAD

**Issue by kalraneeraj24550** [melihberberolu/react-native-scaling-drawer#14]
this is very nice. react-native-scaling-drawer. 
i loved it. 
but i am having a isssue that they are using StackRouter.
and i want to have transition from right to Left when navigate to other screen. 
i dont know how to have transition in StackRouter.

plz help me...

**Comment by kalraneeraj24550** [comment]
in Stack Navigator it is easy. we can use TransmissionConfig option but i dont have idea about doing transition in StackRouter. am begging. i badly need help

**Comment by melihberberolu** [comment]
@kalraneeraj24550 Can you share code ?

**Comment by kalraneeraj24550** [comment]
yes sir, thanku soo much for reply. thanking from my heart. 


import React, { Component } from 'react';
import { Animated,
  Easing,
Platform } from 'react-native';
import ScalingDrawer from 'react-native-scaling-drawer';
import Home from './screens/Home';
import OrderHistory from './screens/OrderHistory';
import LeftMenu from './ContainerMenu/LeftMenu';
import AddtoCart from './screens/AddToCart';
import SecondScreen from './screens/SecondScreen';
import Wine from './screens/Wine';
import MyCart from './screens/MyCart';
import Beer from './screens/Beer';
import Liqour from './screens/Liqour';
import BeerContainer from './screens/BeerContainer';
import Whisky from './screens/Whisky';
import CurrentOrder from './screens/CurrentOrder';
import Login from './screens/Login';
import SignUp from './screens/SignUp';
import Settings from './screens/Settings';
import CustomerAddPlace from './screens/CustomerAddPlace';
import EditProfile from './screens/EditProfile';
import ChangePassword from './screens/ChangePassword';
import LandingScreen from './screens/LandingScreen';
import customerSignup from './screens/customerSignup';
import Products from './screens/Products';
import SplashScreen from './components/SplashScreen';
import {
  createNavigator,
  createNavigationContainer,
  StackRouter,
  createStackNavigator,
  addNavigationHelpers,
  StackNavigator,
} from 'react-navigation';
//import TransitionConfiguration from './components/TransitionConfiguration';
const defaultScalingDrawerConfig = {
  scalingFactor: 0.6,
  minimizeFactor: 0.6,
   swipeOffset: 20,

};

class CustomDrawerView extends Component {
  constructor(props) {
    super(props);
  }

  componentWillReceiveProps(nextProps) {
    /** Active Drawer Swipe **/
    if (nextProps.navigation.state.index === 0)
      this._drawer.blockSwipeAbleDrawer(false);

    if (nextProps.navigation.state.index === 0 && this.props.navigation.state.index === 0) {
      this._drawer.blockSwipeAbleDrawer(false);
      this._drawer.close();
    }

    /** Block Drawer Swipe **/
    if (nextProps.navigation.state.index > 0) {
      this._drawer.blockSwipeAbleDrawer(true);
    }
  }

  setDynamicDrawerValue = (type, value) => {
    defaultScalingDrawerConfig[type] = value;
    /** forceUpdate show drawer dynamic scaling example **/
    this.forceUpdate();
  };

  render() {
    const { routes, index } = this.props.navigation.state;
   const ActiveScreen = this.props.router.getComponentForState(this.props.navigation.state);

    return (
      <ScalingDrawer
        ref={ref => this._drawer = ref}
        content={<LeftMenu navigation={addNavigationHelpers({
          ...this.props.navigation,
          state: routes[index],
          openDrawer: () => this._drawer.open(),
          closeDrawer: () => this._drawer.close()
          })}
          // closeDrawerFun={this.closeDrawer.bind(this)}
          />}
        {...defaultScalingDrawerConfig}
        onClose={() => console.log('close')}
        onOpen={() => console.log('open')}
      >
        <ActiveScreen
          navigation={addNavigationHelpers({
            ...this.props.navigation,
            state: routes[index],
            openDrawer: () => this._drawer.open(),
          })}
          dynamicDrawerValue={(type, val) => this.setDynamicDrawerValue(type, val)}
        />
      </ScalingDrawer>
    )
  }

}

const CollapseExpand = (index, position) => {
  const inputRange = [index - 1, index, index + 1];
  const opacity = position.interpolate({
    inputRange,
    outputRange: [0, 1, 1],
  });

  const scaleY = position.interpolate({
    inputRange,
    outputRange: ([0, 1, 1]),
  });

  return {
    opacity,
    transform: [
      { scaleY }
    ]
  };
};


const SlideFromRight = (index, position, width) => {
  const inputRange = [index - 1, index, index + 1];
  const translateX = position.interpolate({
    inputRange: [index - 1, index, index + 1],
    outputRange: [width, 0, 0]
  })
  const slideFromRight = { transform: [{ translateX }] }
  return slideFromRight;
};

const TransitionConfiguration = () => {
  return {
    transitionSpec: {
      duration: 750,
      easing: Easing.out(Easing.poly(4)),
      timing: Animated.timing,
      useNativeDriver: true,
    },
    screenInterpolator: (sceneProps) => {
      const { layout, position, scene } = sceneProps;
      const width = layout.initWidth;
      const { index, route } = scene;
      const params = route.params || {}; // <- That's new
      const transition = params.transition || 'default'; // <- That's new
      return {
        collapseExpand: CollapseExpand(index, position),
        default: SlideFromRight(index, position, width),
      }[transition];
    },
  };
};

const AppNavigator = StackRouter({
  OrderHistory: { screen: OrderHistory },
  Home: { screen: Home }, 
  Beer: { screen: Beer },
  AddtoCart: { screen: AddtoCart },
  SecondScreen: { screen: SecondScreen },
  BeerContainer: { screen: BeerContainer },
  MyCart: { screen: MyCart },
  Wine: { screen: Wine },
  Whisky: { screen: Whisky },
  Liqour: { screen: Liqour },
  CurrentOrder: { screen: CurrentOrder },
  Login: { screen: Login },
  SignUp: { screen: SignUp },
  Settings: { screen: Settings },
  CustomerAddPlace: { screen: CustomerAddPlace },
  EditProfile: { screen: EditProfile },
  ChangePassword: { screen: ChangePassword },
  LandingScreen: { screen: LandingScreen },
  customerSignup: { screen: customerSignup },
  Products: { screen: Products },
  SplashScreen: { screen: SplashScreen }


}, {
    initialRouteName: 'SplashScreen',
    headerMode: 'screen',
    drawerPosition: 'right',
    mode: Platform.OS === 'ios' ? 'modal' : 'card',
    navigationOptions: {
      cardStack: {
        gesturesEnabled: false
      },
      gesturesEnabled: false
    },
    gesturesEnabled: false,
    
    transitionConfig: TransitionConfiguration,
    });


const CustomDrawer = createNavigationContainer(createNavigator(AppNavigator)(CustomDrawerView));

export default CustomDrawer;


plz help me, here my code

**Comment by kalraneeraj24550** [comment]
transition config is not working , i dont know why, but transition config works in case of stackNavigator .
hiw to do right to left transition in StackRouter

**Comment by melihberberolu** [comment]
Check new example plz.
