### ISSUE TITLE
transitionconfig in stackRouter

### ISSUE THREAD

**Issue by kalraneeraj24550** [melihberberolu/react-native-scaling-drawer#15]
Do you have an example where I can use these custom transitions inside a Custom navigator created using the createNavigationContainer(
createNavigator(AppStackRouter)(StackView)
);

This is based off of CustomTabs example in react-navigation examples. Here I am confused as to how do I pass my transitionConfig inside createNavigator.

here is how I defined my StackRouter( which seems to take the stackConfig which in turn seems to take a StackConfig param as per here .

export const AppStackRouter = StackRouter(defaultMap, {
initialRouteName: 'StartScreenView',
transitionConfig: TransitionConfiguration,
});

But still the console.log (), I wrote inside the screenInterpolator of the transitionConfig is not hit :(. Any thoughts on what I am doing wrong?

UPDATE 2:
Tried a different approach by passing the transition config to teh createNavigator 3rd argument
createNavigationContainer(
createNavigator(AppStackRouter, {}, {transitionConfig: TransitionConfiguration})(StackView)
);

still the console.log inside my screenInterpolator did not get hit . I am officially out of ideas now in trying to get animations to work inside a Custom navigator. I would expect the default stack animations would exist even if we create a custom stack navigator, but turns out it is not the case

**Comment by kalraneeraj24550** [comment]
plz help me

**Comment by melihberberolu** [comment]
Check 
https://github.com/melihberberolu/react-native-scaling-drawer/tree/master/Example
I'm updated example with react navigation v2. I will improve example project and readme.

**Comment by kalraneeraj24550** [comment]
hi thanks for your code. thanku soo much you helped. 
it solved my transition problem.
am facing two issue.
1. on any screen drawer is easy swipeable from left side. there is no lock on some screen. like i want drawer to swipe on some screen and on some screen dont want .
navigationOptions: {
  drawerLockMode: 'locked-closed'  //not working
}  

2. how to open the drawer on click on menu button.
this.props.navigation.openDrawer() not working

**Comment by melihberberolu** [comment]
This drawer doesn't integrated with react-navigation. Check example, I'm using drawer ref. So you can access all function in drawer like open, close etc...

**Comment by kalraneeraj24550** [comment]
sir, as fro closing the drawer
you used,
this.props.drawer.current.close();
for opening the drawer
this.props.drawer.current.open() // this is how i have to write.? but this is not working..

**Comment by melihberberolu** [comment]
export const drawer = createRef();
And give drawer in <ScalingDrawer ref={drawer} />

And access everywhere drawer ref.

**Comment by kalraneeraj24550** [comment]
sir, i 
did
const drawer = createRef();
then i did
drawer.current.open()    // not wkring
drawer.open()  // not working....

sir, will you plz tell me where am doing wrong.  am sorry sir actually am very noob in react-native

**Comment by melihberberolu** [comment]
Okey. I'm updated example. Check home page.

**Comment by kalraneeraj24550** [comment]
thanks sir,,
now it worked. sorry sir disturbed you.
sir, what about swipedrawer on some screen. and on some screen dont want swipedrawer .
this thing is not working
navigationOptions: {
drawerLockMode: 'locked-closed' //not working
}

**Comment by melihberberolu** [comment]
Just look index.js you can see blockDrawer function and call it with drawer ref your component willMount

**Comment by kalraneeraj24550** [comment]
thanks sir, i have two issues. 
1. when i do swipe  to open drawer sometimes drawer gets hanged.
2. sir, when i navigate to other screen , it showing animation. but when i navigate through drawer to other screen i dont want animation...

**Comment by kalraneeraj24550** [comment]
i  have resolved second issue. thanks for your time
