### ISSUE TITLE
Drawer Position

### ISSUE THREAD

**Issue by andy199609** [melihberberolu/react-native-scaling-drawer#22]
Can I put the drawer menu to right hand side?

**Comment by andy199609** [comment]
OK. I found the solution.

Just replace 
this.maxTranslateXValue = Math.ceil(width * props.minimizeFactor);
with
this.maxTranslateXValue = -Math.ceil(width * props.minimizeFactor);
in the node_modules/react-native-scaling-drawer/index.js
Then the drawer will animate in right hand side.

**Comment by hussainMansoor876** [comment]
set props position="right"
