### ISSUE TITLE
Wix native navigation

### ISSUE THREAD

**Issue by odesey** [melihberberolu/react-native-scaling-drawer#5]
Will this work with https://github.com/wix/react-native-navigation ?

Thanks.

**Comment by melihberberolu** [comment]
I don't know. But I think doesn't work with wix-navigation. https://github.com/wix/react-native-navigation/tree/master/ios/RCCDrawerController/TheSidebarController/Animations
u can import this animations for scaling drawer. Like AirbnbAnimation
